# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 623a282234d506c71139bc22c229dde436eb71c01fe7aaa799b48af1681767292557ec941ace16fb828bef5d4dc3fbc401747b174caea05e8ab9d38150631553

test:
  secret_key_base: 0122b4aac91ecc9fb573878b0b56c0638887f5f15a980d954e0c7bcf8c25bc68dc22351068eccf5cac15fa0e8c6c021449a9428a04e81cd0e4c18741e7aee8d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
