# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2fff20fec19cbbd16b3dc3468d9b1cd7ee17ac25e7bcd470c0b7a082236230dc2c0990a2afd4281688ef55662a6eacec9fff86ac905e0bddff4080241862a98

test:
  secret_key_base: 41f0bae77387fb0783f1e0ddeff1c663e94a68945bcc1a67dee2c207f3f7dc1d0108ae0f329ec708d0d5df6cfe5456cc7afc18da3e36f78599b03c5c9ef0d8c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
